services:
  interpreter:
    build: .
    ports:
      - "8123:8123"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../eval/kaggle_data/spooky:/app/spooky:rw
      - ../eval/kaggle_data/jigsaw:/app/jigsaw:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
